name: test_reflectable
# This package is not intended to be published
publish_to: none
description: >
  This package contains tests which depend on package reflectable and
  which are built by the code generation support offered by that
  package. It is not intended to be useful for other purposes than
  testing package reflectable.
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  build_runner: any
  glob: any
  reflectable:
    path: ../reflectable
dev_dependencies:
  analyzer: any
  build_test: any
  lints: any
  test: ^1.25.0
