name: test_reflectable
description: >
  This package contains tests which depend on package reflectable
  and which are transformed by the transformer in that package.
version: 2.0.0-dev.1.0
author: The Dart Team <dart@google.com>
homepage: https://www.github.com/dart-lang/reflectable
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  reflectable:
    path: ../reflectable
  build_runner: ^0.6.1
  glob: ^1.1.5
dev_dependencies:
  unittest: ^0.11.0
transformers:
- $dart2js:
    $include: []
