name: reflectable
version: 3.0.9
description: >
  Reflection support based on code generation, using 'capabilities' to
  specify which operations to support, on which objects.
homepage: https://github.com/google/reflectable.dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  analyzer: ^3.4.1
  build: ^2.0.0
  build_resolvers: ^2.0.0
  build_config: ^1.0.0
  build_runner: ^2.0.1
  build_runner_core: ^7.0.0
  dart_style: ^2.0.0
  glob: ^2.0.0
  logging: ^1.0.0
  package_config: ^2.0.0
  path: ^1.8.0
  source_span: ^1.8.1
dev_dependencies:
  build_test: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0-nullsafety
