name: reflectable
version: 2.2.8
description: >
  Reflection support based on code generation, using 'capabilities' to
  specify which operations to support, on which objects.
homepage: https://www.github.com/dart-lang/reflectable
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  analyzer: '>=0.40.0 <=0.40.4'
  build: ^1.3.0
  build_resolvers: ^1.3.0
  build_config: ^0.4.0
  build_runner: ^1.10.0
  build_runner_core: ^6.0.0
  dart_style: ^1.3.0
  glob: ^1.2.0
  logging: ^0.11.0
  package_config: ^1.1.0
  path: ^1.6.0
  source_span: ^1.5.0
dev_dependencies:
  build_test: ^1.2.0
  pedantic: ^1.9.0
  test: ^1.9.0
