name: reflectable
description: >
  This package allows programmers to reduce certain usages of dynamic
  reflection to a statically specified subset thereof, based on generated
  code with the same behavior as mirrors provided by 'dart:mirrors'. The
  generated code does not use dynamic reflection and thus improves the
  resource economy (esp. by using a smaller amount of space than dart2js
  generated code).
version: 2.0.0-dev.1.0
author: The Dart Team <dart@google.com>
homepage: https://www.github.com/dart-lang/reflectable
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  analyzer: ^0.30.0
  barback: ^0.15.0
  build: ^0.10.2
  build_barback: ^0.4.0
  build_runner: ^0.5.0
  code_transformers: '>=0.4.1 <0.6.0'
  dart_style: '>=0.2.0 <2.0.0'
  glob: ^1.1.0
  logging: ^0.11.0
  path: '>=1.2.0 <1.5.0'
  source_span: '>=1.0.0 <1.5.0'
dev_dependencies:
  unittest: ^0.11.0
transformers:
- $dart2js:
    commandLineOptions: [--show-package-warnings]
    # We do not want to compile anything in this package.
    $include: []
