name: reflectable
version: 4.0.12
description: >
  Reflection support based on code generation, using 'capabilities' to
  specify which operations to support, on which objects.
homepage: https://github.com/google/reflectable.dart
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  analyzer: ^6.8.0
  build: ^2.4.0
  build_resolvers: ^2.4.0
  build_config: ^1.1.0
  build_runner: ^2.4.0
  build_runner_core: ^7.2.0
  dart_style: ^2.3.0
  glob: ^2.1.0
  logging: ^1.2.0
  package_config: ^2.1.0
  path: ^1.9.0
  source_span: ^1.10.0
dev_dependencies:
  build_test: ^2.2.0
  lints: ^5.0.0
  test: ^1.25.0
