name: reflectable
description: >
  This package allows programmers to reduce certain usages of dynamic
  reflection to a transformer generated specialization with the same
  behavior. The generated code does not use dynamic reflection and thus
  improves the performance of (esp. dart2js) generated code.
version: 0.5.3
author: The Dart Team <dart@google.com>
homepage: https://www.github.com/dart-lang/reflectable
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  analyzer: ^0.27.2
  barback: ^0.15.0
  code_transformers: ^0.4.1
  dart_style: ^0.2.0
  glob: ^1.1.0
  logging: ^0.11.0
  path: ^1.2.0
  source_span: ^1.0.0
dev_dependencies:
  unittest: ^0.11.0
transformers:
- reflectable/src/transform_import:
    $include: lib/reflectable.dart
- $dart2js:
    commandLineOptions: [--show-package-warnings]
    # We do not want to compile anything in this package.
    $include: []
