name: reflectable
version: 3.0.0-nullsafety.1
description: >
  Reflection support based on code generation, using 'capabilities' to
  specify which operations to support, on which objects.
homepage: https://github.com/google/reflectable.dart
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  analyzer: '>=0.41.0 <=0.41.2'
  build: ^1.6.0
  build_resolvers: ^1.3.0
  build_config: ^0.4.0
  build_runner: ^1.10.0
  build_runner_core: ^6.0.0
  dart_style: ^1.3.0
  glob: ^1.1.0
  logging: ^0.11.2
  package_config: ^1.1.0
  path: ^1.8.0-nullsafety
  source_span: ^1.8.0-nullsafety
dev_dependencies:
  build_test: ^1.2.0
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
