name: reflectable_builder
vlrsion: 1.1.0
description: >
  Reflection support based on code generation, using 'capabilities' to
  specify which operations to support, on which objects. This is the
  builder part of reflectable.
homepage: https://github.com/google/reflectable.dart
environment:
  sdk: ^3.9.0
resolution: workspace
dependencies:
  analyzer: ^8.0.0
  build: ^4.0.0
  dart_style: ^3.0.0
  pub_semver: ^2.2.0
  path: ^1.9.0
  reflectable: '>=5.1.0 <5.2.0'
dev_dependencies:
  build_config: ^1.1.0
  build_resolvers: ^3.0.4
  build_runner: ^2.4.0
  build_runner_core: ^9.3.2
  glob: ^2.1.0
  lints: ^5.0.0
  logging: ^1.2.0
  package_config: ^2.1.0
  source_span: ^1.10.0
  test: ^1.25.0
platforms:
  windows:
  linux:
  macos:
